### ISSUE TITLE
Error at install

### ISSUE THREAD

**Issue by gybeata** [ssadedin/ximmer#16]
Hello,

I am having a hard time installing xhmm within ximmer. This is the error I am getting:

```
g++ -c -Wall -Werror -O3  -I./sources/include  sources/lib/MatrixDecomp.cpp -o build/lib/MatrixDecomp.o
In file included from sources/lib/MatrixDecomp.cpp:3:0:
./sources/include/VectorOnDisk.hpp: In instantiation of 'HMM_PP::VectorOnDisk<dataType>::~VectorOnDisk() [with dataType = double]':
sources/lib/MatrixDecomp.cpp:75:1:   required from here
./sources/include/VectorOnDisk.hpp:91:37: error: throw will always call terminate() [-Werror=terminate]
        throw new Exception(str.str());
                                     ^
./sources/include/VectorOnDisk.hpp:91:37: note: in C++11 destructors default to noexcept
cc1plus: all warnings being treated as errors
```

Do you have any idea where to look for the source of the error? I was not able to find any useful solution so far. 

Thank you

**Comment by SafinaAr** [comment]
im having the same error this error is particular to xhmm tool

**Comment by ssadedin** [comment]
I've just pushed what I hope might be a fix for this. If you pull down the latest code and try the install process again you can try it again. You might need to remove the existing attempt it made at compiling XHMM, eg:

```
rm -rf eval/pipeline/tools/xhmm
```

Thanks for reporting the problem and let me know if this helps!

**Comment by cluhaowie** [comment]
I have accounted the same error here with latest git clone on ubuntu server 18.04LTS. Here is the gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04), and the error message 
```
g++ -c -Wall -Werror -O3  -I./sources/include  sources/lib/MatrixDecomp.cpp -o build/lib/MatrixDecomp.o
In file included from sources/lib/MatrixDecomp.cpp:3:0:
./sources/include/VectorOnDisk.hpp: In instantiation of ‘HMM_PP::VectorOnDisk<dataType>::~VectorOnDisk() [with dataType = double]’:
sources/lib/MatrixDecomp.cpp:75:1:   required from here
./sources/include/VectorOnDisk.hpp:91:37: error: throw will always call terminate() [-Werror=terminate]
        throw new Exception(str.str());
                                     ^
./sources/include/VectorOnDisk.hpp:91:37: note: in C++11 destructors default to noexcept
```

**Comment by mcv21** [comment]
Hi,

FWIW, I sent the XHMM authors a patch to make their code build on C++11 compilers, so if you take master from their git repo, it will now build on 18.04 (and other systems with modern C compilers).
